## 100 numpy exercises..
### Solving first 30 of them!

In [1]:
# 1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [2]:
# 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)

2.2.2


In [3]:
# 3. Create a null vector of size 10 (★☆☆)
ZZZ = np.zeros(10)
print(ZZZ)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4. How to find the memory size of any array (★☆☆)
ZZZ = np.zeros((10,10))
print("%d bytes" % (ZZZ.size * ZZZ.itemsize))

800 bytes


In [2]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
# python in terminal
import numpy as np
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [10]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
O = np.zeros(10)
O[4] = 1
print(O)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
V7 = np.arange(10,50)
print(V7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
V8 = np.arange(50)
V8 = V8[::-1]
print(V8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
M9 = np.arange(9).reshape(3,3)
print(M9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array10 = np.nonzero([1,2,0,0,4,0])
print(array10)

(array([0, 1, 4]),)


In [4]:
# 11. Create a 3x3 identity matrix (★☆☆)
array11 = np.eye(3)
print(array11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 12. Create a 3x3x3 array with random values (★☆☆)
array12 = np.random.random((3,3,3))
print(array12)

[[[0.07787984 0.68338541 0.7016719 ]
  [0.01352646 0.61742347 0.34919839]
  [0.83909269 0.56482659 0.92402353]]

 [[0.62302269 0.60736851 0.05491245]
  [0.87836358 0.82092515 0.30877199]
  [0.05961121 0.75935997 0.81141935]]

 [[0.1321207  0.13699554 0.63673982]
  [0.58005339 0.84718348 0.16441133]
  [0.84893925 0.34195321 0.66100257]]]


In [6]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array13 = np.random.random((10, 10))
array13min, array13max = array13.min(), array13.max()
print(array13min, array13max)

0.005085798100055494 0.9911685068715482


In [9]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
arr14 = np.random.random(30)
m = arr14.mean()
print(m)

0.42554476806723635


In [10]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
arr15 = np.ones((10,10))
arr15[1:-1,1:-1] = 0
print(arr15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
arr16 = np.ones((5,5))
arr16 = np.pad(arr16, pad_width=1, mode='constant', constant_values=0)
print(arr16)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [12]:
# 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [13]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
arr18 = np.diag(1+np.arange(4), k=-1)
print(arr18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [14]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
arr19 = np.zeros((8,8),dtype=int)
arr19[1::2,::2] = 1
arr19[::2,1::2] = 1
print(arr19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [16]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
arr21 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(arr21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 22. Normalize a 5x5 random matrix (★☆☆)¶
arr22 = np.random.random((5,5))
arr22 = (arr22 - np.mean (arr22)) / (np.std (arr22))
print(arr22)

[[-0.85759364  1.2151769   0.43441151  1.45900453 -1.50513413]
 [ 1.79032774  1.30922173 -0.55430137  1.63497273 -0.5653918 ]
 [-0.35459543 -0.06819832 -0.88563476 -1.15410206 -0.97961417]
 [-1.26064033 -0.15453377 -1.15056096  1.19285543 -0.4442839 ]
 [-0.34590857 -0.00597622  0.56272168  1.22402481 -0.53624764]]


In [18]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("k", np.ubyte, 1)])

In [19]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)¶
arr24 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr24)

# Alternative solution, in Python 3.5 and above
arr24 = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [20]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)¶
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [21]:
# 26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [22]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [23]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Dell\AppData\Local\Temp\ipykernel_4724\4123742269.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Dell\AppData\Local\Temp\ipykernel_4724\4123742269.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Dell\AppData\Local\Temp\ipykernel_4724\4123742269.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [25]:
# 29. How to round away from zero a float array ? (★☆☆)
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 9.64438034  8.7523802   7.66882027 -0.20603165 -3.4988845  -1.1776344
  2.48888191 -6.61370932  5.55982726 -1.23909519]
[10.  9.  8. -1. -4. -2.  3. -7.  6. -2.]


In [38]:
# 30. How to find common values between two arrays? (★☆☆)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 6]


https://www.kaggle.com/code/utsav15/100-numpy-exercises